Better support MSVC .libs by using NULL char terminators when detected
MSVC likes to use NULL character terminators instead of
newlines (\n) for their listing, which causes parsing to not
work correctly, usually with this error:

    arpy.ArchiveFormatError: file references a name not present in the index

This is fixed by detecting NULL character usage and
using that delimiter accordingly.

Some very helpful inspiration that led to figuring this out:
 * https://www.winehq.org/pipermail/wine-patches/2013-April/123863.html (winedump/lib.c)
 * https://substrate.dev/rustdocs/latest/object/pe/
 * http://hmelnov.icc.ru/geos/scripts/WWWBinV.dll/ShowR?COFF_LIB.rfi
 * http://www.textfiles.com/programming/FORMATS/lib.txt
 * https://www.ntcore.com/files/richsign.htm
 * http://bytepointer.com/resources/pietrek_lib_file_format.htm